[package]
name = "droid"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.20", default-features = false }

[dependencies]
chacha20poly1305 = "0.10.1"
sha3 = "0.10.6"
